import { apiGet, apiPost, login } from './api.js';
import { setSession, getSession, clearSession } from './config.js';
import { state } from './state.js';
import { renderRequests, renderTickets, renderIndicators, renderDashboard, setApiStatus } from './ui.js';
const $=s=>document.querySelector(s);let deferredPrompt=null;
function showApp(){ $('#loginView').classList.add('hidden');$('#appShell').classList.remove('hidden') }
function showLogin(){ $('#appShell').classList.add('hidden');$('#loginView').classList.remove('hidden') }
async function health(){const d=await apiGet('health');setApiStatus(true,`API V${d.version||'4'} ativa`);return d}
async function loadAll(sync=false){try{if(sync){const s=await apiPost('sync');$('#syncResult').textContent=`Sincronização: ${s.result?.added||0} novos e-mails, ${s.result?.autoReplies||0} respostas automáticas.`;$('#syncResult').classList.remove('hidden')}const [req,tic,ind]=await Promise.all([apiGet('list'),apiGet('tickets'),apiGet('indicators')]);state.setRequests(req.items||[]);state.setTickets(tic.items||[]);state.setIndicators(ind.indicators||{});renderRequests();renderTickets();renderIndicators();renderDashboard();setApiStatus(true)}catch(e){if(/sessão|token|autorizad/i.test(e.message)){clearSession();showLogin()}else alert(e.message)}}
function initNavigation(){document.querySelectorAll('.nav-btn').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.app-view').forEach(v=>v.classList.toggle('active',v.id===`view-${button.dataset.view}`))}))}
function initLogin(){ $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMessage').textContent='Validando...';try{const data=await login($('#loginUser').value,$('#loginPassword').value);setSession(data.token);showApp();await loadAll(true)}catch(err){$('#loginMessage').textContent=err.message}});$('#logoutBtn').addEventListener('click',()=>{clearSession();showLogin()}) }
function initFilters(){['searchInput','typeFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderRequests))}
function openTicket(){ $('#ticketDialog').showModal() }
function initTicket(){ $('#openTicketBtn').addEventListener('click',openTicket);$('#openTicketBtn2').addEventListener('click',openTicket);$('#cancelTicket').addEventListener('click',()=>$('#ticketDialog').close());$('#ticketForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await apiPost('open_ticket',data);e.currentTarget.reset();$('#ticketDialog').close();await loadAll(false);alert('Chamado enviado e registrado.')}) }
function initDocuments(){ $('#sendDocumentBtn').addEventListener('click',()=>$('#documentDialog').showModal());$('#cancelDocument').addEventListener('click',()=>$('#documentDialog').close());$('#documentForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await apiPost('send_document',data);e.currentTarget.reset();$('#documentDialog').close();alert('Documento enviado.')}) }
function initIndicators(){ $('#refreshIndicatorsBtn').addEventListener('click',()=>loadAll(false));$('#openIndicatorsSheetBtn').addEventListener('click',async()=>{const d=await apiGet('indicators_sheet');window.open(d.url,'_blank','noopener')}) }
function initPwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')})}
$('#syncBtn').addEventListener('click',()=>loadAll(true));$('#closeDetail').addEventListener('click',()=>$('#detailDialog').close());window.addEventListener('gases:refresh',()=>loadAll(false));initNavigation();initLogin();initFilters();initTicket();initDocuments();initIndicators();initPwa();
(async()=>{try{await health()}catch(e){setApiStatus(false,'API indisponível');$('#loginMessage').textContent='Backend indisponível. Verifique a implantação do Apps Script.'}if(getSession()){try{showApp();await loadAll(false);return}catch{clearSession()}}showLogin()})();
